---
- name: Include domain list from vars
  include_vars:
    file: var/domains.txt
- name: Read domains from file
  slurp:
    src: vars/domains.txt
  register: domain_file_content

- set_fact:
    domains: "{{ domain_file_content['content'] | b64decode | split('\n') }}"


- name: Create DNS records for custom domains
  win_dns_record:
    name: "{{ item }}"
    type: "A"
    value: "10.0.0.10"
    zone: "sre.local"
  loop: "{{ domains }}"
