---
- name: List name record domain
  include_vars:
    file: ../../../global_vars/domains.yaml

- name: Create list domain
  win_dns_record:
    name: "{{ item }}"
    type: "{{ typeRecord }}"
    value: "{{ ipNginx }}"
    zone: "{{ domainName }}"
  loop: "{{ domains }}"
