---
- name: List name record domain
  include_vars:
    file: var/domains.yaml

- name: IP nginx
  include_vars:
    file: var/ip-nginx.yaml

- name: Create list domain
  win_dns_record:
    name: "{{ item }}"
    type: "A"
    value: "{{ ip }}"
    zone: "sre.local"
  loop: "{{ domains }}"
